### PR TITLE
Changed type of passedDeviceId on url-params

### PR DESCRIPTION
**Pull request by laziob**
Change passdeviceId variable to let it be undefined instead of null on url-params.ts

Change Type: Minor
Signed-off-by: Ezequiel Boehler ezequiel@balena.io

### CODE REVIEW

**Comment by gelbal** [comment]
@laziob can you please rebase before committing your changes?
This PR now includes my previous PR. 

Also, good to note that we don't do manual edits / commits on Changelog file. Versionbot auto updates it after the PR is merged.

**Comment by laziob** [comment]
@gelbal  Yes my bad. I tried to leave the branch in such a way that only my last changes where commited and not the ones I pulled from master (your last PR) but didnt seem to work, it always add those changes to this commit

**Comment by gelbal** [comment]
I don't know what went wrong here @laziob. Can you please try again by starting from scratch? 
I'd do:
1. (On master) `git fetch && git pull`
2. Create new branch `git checkout -b fix-type-error-deviceid`
3. Commit changes and force push to this branch.

**Comment by gelbal** [comment]
Closed in favor of https://github.com/balena-io-modules/analytics-client/pull/44

**Pull request closed without merging**
